---
users_list:
  - user: alf
    homedir: /home/alf
  - user: duchess
    homedir: /home/duchess
  - user: skipper
    homedir: /home/skipper
  - user: snafu
    homedir: /home/snafu
  - user: xander.harris
    homedir: /home/xander.harris
users_files:
  - .bash_profile
  - .bashrc
  - .gitconfig
  - .vimrc
